### ISSUE TITLE
fire event when label is passed while still moving/dragging.

### ISSUE THREAD

**Issue by targor** [karenpommeroy/rangeslide.js#4]
Hi,

at first i like this slider really much, but i would like to know if it is possible to make the slider behave like the following:

Can the slider fire an event when the slider is over a label but constantly being moved to a final position?
i tried the "thumbDragged" event, but this is not fired at all and maybe is not what i wanted at all?

**Comment by karenpommeroy** [comment]
There was a little bug with thumbDragged event. It's fixed in v13.0.1
